services:
  postgresdb:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=wordcloud_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:3.12.8-management-alpine'
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
    ports:
      - '5672:5672'
      - '15672:15672'
  core:
    build:
      context: './'
      dockerfile: 'Dockerfile'
    depends_on:
      - 'postgresdb'
      - 'rabbitmq'
    environment:
      - 'POSTGRES_DB=wordcloud_db'
    ports:
      - '8000:8080'
  worker:
    build:
      context: '../bitweb-worker'
      dockerfile: 'Dockerfile'
    depends_on:
      - 'postgresdb'
      - 'rabbitmq'
      - 'core'
    #deploy:
    #  replicas: 2
    environment:
      - 'POSTGRES_DB=wordcloud_db'
  frontend:
    build:
      context: '../bitweb-frontend'
      dockerfile: 'Dockerfile'
    ports:
      - '5173:5173'
